[terminology]
threads=16 #number of threads used for sending https requests to terminologies.gfbio.org
url_search="https://terminologies.gfbio.org/api/terminologies/search" #base url for http requests to search api of terminologies